name = "eklavya-portfolio-content"
main = "src/index.js"
compatibility_date = "2026-09-27"

[[d1_databases]]
binding = "DB"
database_name = "eklavya-portfolio"
database_id = "034f85d6-ba39-4796-a56d-3cdf1ace4f84"

[vars]
SITE_ORIGIN = "https://eklavya.dpdns.org"
